### PR TITLE
Allow users to switch to Kitura-NIO

### PR DESCRIPTION
**Pull request by mamabusi**
Allow users to switch to use Kitura-NIO by setting the environment variable KITURA_NIO.

### CODE REVIEW

**Comment by ianpartridge** [comment]
Please add KituraNIO testing to Travis CI :)

**Comment by mamabusi** [comment]
@ianpartridge Have added the travis changes. Please take a look. Thanks.

**Comment by ianpartridge** [comment]
Travis is failing because this PR is opened from mamabusi:addNioSupport-branch

You should push your branch to IBM-Swift and open the PR from there instead, please.

**Comment by mamabusi** [comment]
I just noticed that PR: https://github.com/IBM-Swift/Kitura-CouchDB/pull/81 is doing the same and this is a repeat. Please feel free to merge that PR if it looks good.

**Comment by mamabusi** [comment]
Created #83 that has the changes from a branch of IBM-Swift. Closing this PR.

**Pull request closed without merging**
