### PR TITLE
Fixed a typo, re-indented the code, .Schema to https (if secure)

### PR DESCRIPTION
**Pull request by samwarfield**
Indented the code so its all uniform.

Updated the CouchDBUtils so the prepare request options will set the .Schema to https (instead of http) if secure is set to true…

### CODE REVIEW

**Comment by kweinmeister** [comment]
Thanks for the PR @samwarfield! Can you please fill out the [CLA form](https://github.com/IBM-Swift/CLA) so we can review it?

**Comment by samwarfield** [comment]
@kweinmeister Hey, I just emailed the form as you requested.

**Comment by kweinmeister** [comment]
Got it, thanks @samwarfield!

**Comment by samwarfield** [comment]
##### Description

Indented the code so its all uniform.

Updated the CouchDBUtils so the prepare request options will set the .Schema to https (instead of http) if secure is set to true…

##### Motivation and Context

Wanted to make it easier to read and fix some typos. The connection to the database wasn't using https when setting secure = true.

##### How Has This Been Tested?

The test I ran was setting "secure = true" in ConnectionProperties and pointing to a Cloudant service.

##### Checklist:
- [x] I have submitted a CLA form
- [ ] If applicable, I have updated the documentation accordingly.
- [ ] If applicable, I have added tests to cover my changes.

**Comment by shmuelk** [comment]
We've started looking at the outstanding PRs.

I have a couple issues with your PR:
  1) In general we only take PRs against our develop branch, not against master.
  2) You mixed branches of code. You changed in Package.swift, to use Kitura-Net 0.9.x. Odd releases are from our develop branch, while you were doing a PR on our master branch.
  3) You change to fix the use of http even secure=true was specified, was already fixed by a prior PR.

Please "rebase" the rest of your changes on the current code in our develop branch and issue the PR against that branch.

**Pull request closed without merging**
