### PR TITLE
ci: Update to 4.2.3, official Docker images and enable NIO testing

### LINKED ISSUE #91: CouchDB Kitura NIO tests failing on Linux
There was a missing return statement in the CouchDB tests. This was causing the tests to automatically pass without actually running. 
A pr fixing this has been raised [here](https://github.com/IBM-Swift/Kitura-CouchDB/pull/87)

Now the tests are running the KituraNio travis builds are failing.

We need to investigate why they are failing and either fix them or propose a new solution for making rest requests within this repo.

### PR DESCRIPTION
**Pull request by djones6**
## Description

- Update to official Swift Docker images (speeds up build time)
- Update to Swift 4.2.3
- Re-enable NIO mode testing now that https://github.com/IBM-Swift/Kitura-NIO/pull/171 and https://github.com/IBM-Swift/Kitura-NIO/pull/172 are merged.

## Motivation and Context

Resolves #91 

## Checklist:

- [ ] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [ ] If applicable, I have updated the documentation accordingly.
- [ ] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by pushkarnk** [comment]
@djones6 The only failure in the latest run is with NIO on macOS, which seems to be due to the unavailability of openssl. I think we'd need to add `BREW_INSTALL_PACKAGES="libressl"` to the corresponding Travis step.

**Comment by djones6** [comment]
@pushkarnk Thanks - CI is running clean now, so this is ready to review/merge.

**Review by pushkarnk — APPROVED** [review]
LGTM. Just one question. We seem to have removed all 14.04 builds from Travis. Was that intended?

**Comment by djones6** [comment]
@pushkarnk The removal of 14.04 builds is due to 14.04 shortly going out of service.  There will be extended support as a paid offering, but I expect Kitura users will migrate (or have already migrated) to 16.04 or higher.  The official Swift Docker images are based on 16.04.

I submitted https://github.com/IBM-Swift/Kitura/pull/1429 to restore one permutation of 14.04 testing for the Kitura repo (this will also cover all Kitura's dependencies), and will retain one similarly in Kitura-Sample (which has a broader set of dependencies including Stencil, Sessions, Credentials, SwiftMetrics - though not CouchDB).

I could be persuaded to reintroduce 14.04 to a broader set of repos if we feel there's real risk of breakage in the future.  At the moment I see it as very low risk, confined to places where we directly interact with C libraries (curl, openssl, zlib) that are back-level on 14.04.

**Pull request merged**
