### PR TITLE
Added some functionality to use the "_users" database

### PR DESCRIPTION
**Pull request by samwarfield**
## Description

I made a subclass of Database.swift called UserDatabase.swift. It is used to just interact with the "_users" database to add a new user and get the session token from CouchDB. I updated the readme with an simple example of usage.
## Motivation and Context

I wanted to add users to the "_users" database in CouchDB and get a session token from CouchDB for the user.
## How Has This Been Tested?

I have tested this on my local machine with a private CouchDB. A test to the DBTests.swift file has not been added.
## Checklist:
- [x] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [x] If applicable, I have updated the documentation accordingly.
- [ ] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by rolivieri** [comment]
Thanks for the pull request! A few observations:

1) Since you added a method for setting a config value (config() method in the CouchDBClient class), can you also add another method for reading a config value?

2) The callback for the new config() method (callback: (Bool, NSError?)) can be defined as
 callback: (NSError?). This would remove the need for the Bool variable. If an error occurred, then the optional NSError variable should contain an error. Can you make this change?

3) Once you have methods for reading (getConfig()) and setting (setConfig()) config values and modified the callback definition, can you add test cases for these? As reference, here’s the documentation for these: http://docs.couchdb.org/en/stable/api/server/configuration.html.

4) Can you also add a READ user method to the UsersDatabase?

5) Can you add automated test cases for adding and reading users?

6) Can you remove any print statements from the code such as the print(requestBody)in the createUser() method?

7) Regarding the session methods (http://docs.couchdb.org/en/stable/api/server/authn.html) in the UsersDatabase class, since those methods are not hitting the _users database, can you move them to the CouchDBClient (just like the config methods)?

8) Can you rename the session methods to getSession, createSession, deleteSession?

9) Can you add test cases for the session methods too?

10) Once you have all the test cases, can you ensure the code runs on OS X and Ubuntu operating systems?

**Comment by samwarfield** [comment]
@rolivieri I will work on these changes

**Comment by samwarfield** [comment]
- [x] Since you added a method for setting a config value (config() method in the CouchDBClient class), can you also add another method for reading a config value?
- [x] The callback for the new config() method (callback: (Bool, NSError?)) can be defined as
  callback: (NSError?). This would remove the need for the Bool variable. If an error occurred, then the optional NSError variable should contain an error. Can you make this change?
- [x] Once you have methods for reading (getConfig()) and setting (setConfig()) config values and modified the callback definition, can you add test cases for these? As reference, here’s the documentation for these: http://docs.couchdb.org/en/stable/api/server/configuration.html.
- [x] Can you also add a READ user method to the UsersDatabase?
- [ ] Can you add automated test cases for adding and reading users?
- [x] Can you remove any print statements from the code such as the print(requestBody)in the createUser() method?
- [x] Regarding the session methods (http://docs.couchdb.org/en/stable/api/server/authn.html) in the UsersDatabase class, since those methods are not hitting the _users database, can you move them to the CouchDBClient (just like the config methods)?
- [x] Can you rename the session methods to getSession, createSession, deleteSession?
- [ ] Can you add test cases for the session methods too?
- [ ] Once you have all the test cases, can you ensure the code runs on OS X and Ubuntu operating systems?

**Comment by shmuelk** [comment]
Merged into develop in https://github.com/IBM-Swift/Kitura-CouchDB/commit/5f2e15d3436915d815185d064bd446ff13f0130d

See IBM-Swift/Kitura#462

**Pull request closed without merging**
