### PR TITLE
Query parameters case keys fix #8

### LINKED ISSUE #8: Database.swift/QueryParameters case Keys ([AnyObject]) does not compile in linux
error: value of type 'String' does not conform to expected element type 'AnyObject'
# if os(Linux)

```
case Keys ([Any])
#else
case Keys ([AnyObject])
#endif
```
# if os(Linux)

```
case EndKey (Any)
#else
case EndKey (AnyObject)
#endif
```
# if os(Linux)

   case StartKey (Any)
    #else
    case StartKey (AnyObject)
    #endif

public func queryByView(view: String, ofDesign design: String, usingParameters params: [Database.QueryParameters], callback: (JSON?, NSError?) -> ()) {
    var paramString = ""
    #if os(Linux)
    var keys: [Any]?
    #else
    var keys: [AnyObject]?
    #endif

// other code goes here.
}

### PR DESCRIPTION
**Pull request by samwarfield**
## Description

Update Database.swift to work when querying by views and using the .Key parameters. 
- Changed the StartKey/EndKey to `Any` type.
- Changed the Keys to `[Any]`
- Changed the types from `Array<Any>` to `[Any]`
## Motivation and Context

Reference to issue #8 
## How Has This Been Tested?

Tested manually on both OS X and Ubuntu with the 04/25 drop of Swift. I have added a test.
## Checklist:

- [x] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [x] If applicable, I have updated the documentation accordingly.
- [ ] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by samwarfield** [comment]
I am working on adding more tests. I'd like to figure out how to take advantage of the Travis CI server.

**Comment by shmuelk** [comment]
Thanks for the PR. There have been some changes since you submitted the PR, can you please re-merge and resolve the conflicts.

Also please make sure that you test using the 04/25 drop of Swift

**Comment by samwarfield** [comment]
@shmuelk I am still learning about your CI checks for pull request. How can I take advantage of your CI check for my PR?

**Comment by dfirsht** [comment]
Hey @samwarfield there is currently an issue with running the CI on PRs for CouchDB. We leverage environment variables which are disables during PR checks for security reasons. Thus for now there is no way to pass the CI check.

**Comment by samwarfield** [comment]
@dfirsht Ok, no problem...

**Comment by irar2** [comment]
Merged: https://github.com/IBM-Swift/Kitura-CouchDB/commit/ef3ec7a91adb2dd1aac33eb67f788264d4a095ae
Thanks.

**Pull request closed without merging**
