### PR TITLE
added methods to set/get a database's _security doc

### PR DESCRIPTION
**Pull request by nikwest**
## Description

added two method to database to allow to retrieve and update a database's security doc.

## Motivation and Context

I need to programmatically add a user to a database.

## How Has This Been Tested?

I tested this on Mac OS X with CouchDB 2.0 installed locally.

## Checklist:

- [x] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [ ] If applicable, I have updated the documentation accordingly.
- [ ] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by shmuelk** [comment]
Thank you for PR to help improve Kitura-CouchDB.

Can you add a pair of tests for those two new functions you wrote? Don't worry if the Travis CI test fails for you, it is normal for people outside the core Kitura group.

**Comment by nikwest** [comment]
I can do this. It will take some time as I'm traveling the next weeks though. 

Greetings 

Dominik

**Comment by shmuelk** [comment]
@nikwest Have you had a chance to write the tests for the functions you've added to Kitura-CouchDB?

**Comment by Andrew-Lees11** [comment]
Thank you for the time raising this fix however, I am closing this PR since it is now out of date with CouchDB 3.0.0
The ability to update a database's security doc would be part of issue #89 to allow connection to the database through session and users logging in. This would allow the programmatic addition of users that you requested.
We are not looking to implement this in the immediate future however I would be happy to help if you would like to raise a new PR to solve this issue with the new API.

**Pull request closed without merging**
